# Generated by Django 2.2 on 2019-04-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='preço',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
